version: '3.8'
services: # using compose namespace
  wordpress:
    image: "wordpress:latest"
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_NAME=exampledb
      - WORDPRESS_DB_PASSWORD=examplepass
      - WORDPRESS_DB_USER=exampleuser
    volumes:
      - "/path/to/your/local/wp-data:/var/www/html"
    ports:
      - "8080:80" # using compose namespace
  db:
    image: "mysql:latest"
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=exampledb
      - MYSQL_PASSWORD=examplepass
      - MYSQL_ROOT_PASSWORD=examplepass
      - MYSQL_USER=exampleuser
    volumes:
      - "/path/to/your/local/db-data:/var/lib/mysql"
    ports:
      - "3306:3306"

networks:
  my-network: # using global
    driver: bridge